# Generated by Django 2.0.3 on 2018-04-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_genre',
            new_name='album_title',
        ),
    ]
